async def patchNotes(channelServer, client):
  antriNotes = '07/11/2021 patch notes:\nPraėjo kelios savaitės po paskutinio didelio update, todėl stengiausi pridėti naujų dalykų per šį savaitgalį.\nŠtai yra kelios naujienos:\n 1. Dauguma jau žino, kad perrašiau visą boto kodą (virš 1000 eilučių) į žymiai tvarkingesnį formatą, kuris pagreitina visą veikimą ir palengvina man darbą kuriant naujus dalykus (kaip šis update).\n2. Taip pat tai ne naujiena, kad botas veikia 2x greičiau ir niekada nebeišsijungia (nebent discordo problemos) pats! Tai buvo įmanoma padaryti dėl to, kad nusipirkau premium subscribtioną ant puslapio, kuriame rašau šio boto kodą.\n3. Ko gero svarbiausia šio update naujiena:\nPridėta visiškai nauja ir originali šalių statymo sistema! Nuo šiol kiekvieną pirmadienį, trečiadienį bei šeštadienį bus galimybė statyti ant išrinktų šalių. Norint sužinoti daugiau informacijos, parašyk ``!r šalys help``. Ši sistema nėra labai intensyviai patikrinta, todėl gali būti keletą problemų pirmąją evento dieną (pirmadienį).\n\n\n'
  NaujausiNotes = '23/01/2022\n NAUJAS UPDATE \n·Nuo dabar, kiekvienas penktadienis bus Laimingasis Penktadienis. Tai reiškia, kad tą dieną visi daily bus 10 kartu labiau verti (yup 10 kartų).\nLAIMINGOJO PENKTADIENIO DAILY LENTELĖ:\n```30% - 10,000\n5% - 15,000\n30% - 20,000\n15% - 30,000\n14% - 40,000\n6% - 300,000```\n·Nuo dabar bus galima statyti tik ant vienos šalies ir prizas bus pastatyta suma * 5 (ankšciau buvo * 4).\n\n\n'
  seniausiNotes = '25/09/2021\n1. Pridėta komanda !r coinflip skaicius/herbas random (bet koks skaicius iš tavo pinigų kiekio(atsargiai)).\n2. Mokesčių sistema. Kiekviena antradienį yra surenkami 5% pinigų iš kiek vieno žmogaus, kuris turi daugiau negu 1 mil. pinigų, bet ne daugiau kaip 15mil. Tie kurie turi daugiau negu 15 mil, turi mokėti 10%. Ta pinigų suma keliauja i fondą ir yra išskirstoma žmonėms kurie nėra labai turtingi.\n3. Pridėta !r patchnotes komanda, kuri rodo tris naujausius patch notes.\n\n\n'
  await channelServer.send(seniausiNotes + antriNotes + NaujausiNotes)

async def help(channelServer):
  await channelServer.send('```Pirmas kartas žaidžiant? Parašyk !r addme. \nNori žaisti monetų metimą? Parašyk !r coinflip "herbas/skaičius" "pinigų suma/random"(be kabučių).\nNori žaisti ruletę? Rašyk !r roulette "juoda/raudona/lyginis/nelyginis/žalia" "suma"(be kabučių)\nNori sužinoti kiek liko pinigų? Parašyk !r balance.\nNori gauti dieninį bonusą? Rašyk !r daily.\nPraradai visus pinigus? Rašyk !r praradau.\nNori pervesti kažkam pinigų? Rašyk !r send @žmogus suma.\nNori sužinoti, kokie yra 5 turtingiausi žmonės? Rašyk !r leaderboard\nNori mesti daugiau monetų vienu metu? Rašyk !r coinflip "herbas/skaičius" "pinigų suma" "monetų skaičius" (be kabučių) (monetų limitas yra 150)\nNori spėti numerį pasirinktame intervale? Rašyk !r numeris "spėjamas numeris" "statoma suma" "iki kokio skaičiaus yra intervalas (turi būti lyginis skaičius, mažesnis už 100)" (be kabučių).\nNori pirkti/parduoti DOGE kriptovaliutą? Rašyk !r doge buy/sell(minimalus pirkimo kiekis yra 500) kiekis (rekomenduojama pirkti dideliais kiekiais, nes balansas yra suapvalinamas).\nNori sužinoti kiek yra vertas DOGE? Rašyk !r kainos.\nNori išbandyti savo sėkmę lošimų automatuose? Rašyk !r slots.\nNori sužinoti lošimo bei laimėjimo sumas? Parašyk !r slots help\nNori sužinoti, kas daugiausiai laimėjo lošimo automatuose? Rašyk !r slots leaderboard\nNori sužinoti savo slot laimėjimus? Rašyk !r slots check\nNori dalyvauti savaitiniame evente? Rašyk !r event.\nParašyk !r šalys help, kad sužinoti visą informaciją apie šalių statymo eventą.```')

async def slotsHelp(channelServer):
  await channelServer.send("Sukimo kaina: 500 pinigų.\n<:diamond1:860229741861011466> -- --: 750 pinigų.\n<:diamond1:860229741861011466> <:diamond1:860229741861011466> --: 2500 pinigų.\n<:diamond1:860229741861011466> <:diamond1:860229741861011466> <:diamond1:860229741861011466>: 125000 pinigų.\n:cherries: :cherries:  :cherries: : 6250 pinigų.\n:grapes:  :grapes:  :grapes: : 12500 pinigų.\n:watermelon: :watermelon: :watermelon:: 17500 pinigų.\n:bell: :bell: :bell:: 25000 pinigų.\n<:7nr:860229154363539466> <:7nr:860229154363539466> <:7nr:860229154363539466>: 65000 pinigų.\n")

async def eventHelp(channelServer):
  await channelServer.send("Šis eventas padės žmonėms susigrąžinti prarastus pinigus! Visą savaitę x% prarastų pinigų eis į prize poolą (jeigu nori sužinoti tikslius procentus, rašyk !r event pool). Savaitės gale (sekmadienį) bus išrinkti trys žmonės, kurie gaus dalį šios sumos (60%, 30%, 10%). Norint dalyvauti šiame evente, reikia nusipirkti bilietą (bilietas galioja tik tą savaitę. Jo kaina - 50000 pinigų). Bilietą reikia pirkti rašant !r ticket buy. Taip pat parašydamas !r tickets gali sužinoti kokie žmonės yra nusipirkę po bilietą.")